-- Security and performance pass 2
create index if not exists enrollments_student_course_idx on public.enrollments(student_id,course_id) where status='active';create index if not exists course_staff_profile_course_idx on public.course_staff(profile_id,course_id);create index if not exists materials_course_status_created_idx on public.materials(course_id,status,created_at desc);create index if not exists announcements_course_published_idx on public.announcements(course_id,published_at desc);create index if not exists assignments_course_due_idx on public.assignments(course_id,due_at);create index if not exists submissions_student_assignment_idx on public.submissions(student_id,assignment_id);
-- A user must never be able to promote their own role or change university ownership fields.
revoke update on public.profiles from authenticated;grant update(full_name,updated_at) on public.profiles to authenticated;
drop policy if exists "profile updates self" on public.profiles;create policy "profile updates safe fields" on public.profiles for update to authenticated using(id=auth.uid() and is_active) with check(id=auth.uid() and role=public.current_role());
-- Separate course operations; faculty can edit assigned courses but only admins create/delete them.
drop policy if exists "staff manage courses" on public.courses;create policy "admins create courses" on public.courses for insert to authenticated with check(public.current_role()='admin' and created_by=auth.uid());create policy "assigned staff update courses" on public.courses for update to authenticated using(public.teaches_course(id)) with check(public.teaches_course(id));create policy "admins delete courses" on public.courses for delete to authenticated using(public.current_role()='admin');
-- Storage path must begin with a course UUID that the current user teaches.
drop policy if exists "staff upload course files" on storage.objects;drop policy if exists "staff update course files" on storage.objects;drop policy if exists "staff delete course files" on storage.objects;create policy "assigned staff upload course files" on storage.objects for insert to authenticated with check(bucket_id='course-materials' and (storage.foldername(name))[1] is not null and public.teaches_course(((storage.foldername(name))[1])::uuid));create policy "assigned staff update course files" on storage.objects for update to authenticated using(bucket_id='course-materials' and public.teaches_course(((storage.foldername(name))[1])::uuid)) with check(bucket_id='course-materials' and public.teaches_course(((storage.foldername(name))[1])::uuid));create policy "assigned staff delete course files" on storage.objects for delete to authenticated using(bucket_id='course-materials' and public.teaches_course(((storage.foldername(name))[1])::uuid));
update storage.buckets set file_size_limit=26214400 where id='course-materials';
