begin;

-- Admin-managed academic structure.
create policy "admins manage colleges" on public.colleges for all to authenticated using(public.current_role()='admin') with check(public.current_role()='admin');
create policy "admins manage departments" on public.departments for all to authenticated using(public.current_role()='admin') with check(public.current_role()='admin');
create policy "staff read enrolled student profiles" on public.profiles for select to authenticated using(id=auth.uid() or public.current_role()='admin' or exists(select 1 from public.enrollments e join public.course_staff cs on cs.course_id=e.course_id where e.student_id=profiles.id and cs.profile_id=auth.uid()));
create policy "admins update profiles" on public.profiles for update to authenticated using(public.current_role()='admin') with check(public.current_role()='admin');
grant insert,update,delete on public.colleges,public.departments to authenticated;
grant update(role,is_active,current_level,college_id,department_id,university_id,updated_at) on public.profiles to authenticated;

-- Assignment submission files.
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('assignment-submissions','assignment-submissions',false,26214400,array['application/pdf','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/zip','image/jpeg','image/png']) on conflict(id) do update set public=false,file_size_limit=26214400,allowed_mime_types=excluded.allowed_mime_types;
create policy "students upload own submissions" on storage.objects for insert to authenticated with check(bucket_id='assignment-submissions' and public.is_active_user() and public.try_uuid((storage.foldername(name))[1])=auth.uid());
create policy "owners and staff read submissions" on storage.objects for select to authenticated using(bucket_id='assignment-submissions' and public.is_active_user() and (public.try_uuid((storage.foldername(name))[1])=auth.uid() or public.teaches_course((select a.course_id from public.assignments a where a.id=public.try_uuid((storage.foldername(name))[2])))));
create policy "students update own submissions" on storage.objects for update to authenticated using(bucket_id='assignment-submissions' and public.try_uuid((storage.foldername(name))[1])=auth.uid()) with check(bucket_id='assignment-submissions' and public.try_uuid((storage.foldername(name))[1])=auth.uid());

-- Quizzes: answer keys are isolated from student-readable questions.
create table public.quizzes(id uuid primary key default gen_random_uuid(),course_id uuid not null references public.courses on delete cascade,title text not null,instructions text,duration_minutes integer not null default 20 check(duration_minutes between 1 and 240),max_attempts integer not null default 1 check(max_attempts between 1 and 20),is_published boolean not null default false,created_by uuid not null references public.profiles,created_at timestamptz not null default now());
create table public.quiz_questions(id uuid primary key default gen_random_uuid(),quiz_id uuid not null references public.quizzes on delete cascade,prompt text not null,options jsonb not null check(jsonb_typeof(options)='array' and jsonb_array_length(options)>=2),position integer not null default 1);
create table public.quiz_answer_keys(question_id uuid primary key references public.quiz_questions on delete cascade,quiz_id uuid not null references public.quizzes on delete cascade,position integer not null,correct_index integer not null check(correct_index>=0));
create table public.quiz_attempts(id uuid primary key default gen_random_uuid(),quiz_id uuid not null references public.quizzes on delete cascade,student_id uuid not null references public.profiles on delete cascade,answers jsonb not null,score numeric(5,2) not null,submitted_at timestamptz not null default now());
create index quizzes_course_idx on public.quizzes(course_id,created_at desc);create index quiz_attempts_student_idx on public.quiz_attempts(student_id,quiz_id,submitted_at desc);
alter table public.quizzes enable row level security;alter table public.quiz_questions enable row level security;alter table public.quiz_answer_keys enable row level security;alter table public.quiz_attempts enable row level security;
create policy "relevant users read quizzes" on public.quizzes for select to authenticated using(public.is_active_user() and (public.teaches_course(course_id) or (is_published and exists(select 1 from public.enrollments e where e.course_id=quizzes.course_id and e.student_id=auth.uid() and e.status='active'))));
create policy "staff manage quizzes" on public.quizzes for all to authenticated using(public.teaches_course(course_id)) with check(public.teaches_course(course_id) and created_by=auth.uid());
create policy "relevant users read quiz questions" on public.quiz_questions for select to authenticated using(exists(select 1 from public.quizzes q where q.id=quiz_id));
create policy "staff manage quiz questions" on public.quiz_questions for all to authenticated using(exists(select 1 from public.quizzes q where q.id=quiz_id and public.teaches_course(q.course_id))) with check(exists(select 1 from public.quizzes q where q.id=quiz_id and public.teaches_course(q.course_id)));
create policy "staff manage answer keys" on public.quiz_answer_keys for all to authenticated using(exists(select 1 from public.quizzes q where q.id=quiz_id and public.teaches_course(q.course_id))) with check(exists(select 1 from public.quizzes q where q.id=quiz_id and public.teaches_course(q.course_id)));
create policy "students read own attempts" on public.quiz_attempts for select to authenticated using(student_id=auth.uid() or exists(select 1 from public.quizzes q where q.id=quiz_id and public.teaches_course(q.course_id)));
grant select,insert,update,delete on public.quizzes,public.quiz_questions,public.quiz_attempts to authenticated;grant select,insert,update,delete on public.quiz_answer_keys to authenticated;
create or replace function public.create_quiz_with_questions(p_course_id uuid,p_title text,p_duration integer,p_questions jsonb) returns uuid language plpgsql security definer set search_path=public,pg_catalog as $$declare qid uuid; item jsonb; question_id uuid; pos integer:=0;begin if not public.teaches_course(p_course_id) then raise exception 'Not allowed';end if;insert into public.quizzes(course_id,title,duration_minutes,is_published,created_by) values(p_course_id,left(trim(p_title),160),p_duration,true,auth.uid()) returning id into qid;for item in select * from jsonb_array_elements(p_questions) loop pos:=pos+1;insert into public.quiz_questions(quiz_id,prompt,options,position) values(qid,item->>'prompt',item->'options',pos) returning id into question_id;insert into public.quiz_answer_keys(question_id,quiz_id,position,correct_index) values(question_id,qid,pos,(item->>'correct_index')::integer);end loop;return qid;end$$;
create or replace function public.submit_quiz_attempt(p_quiz_id uuid,p_answers jsonb) returns jsonb language plpgsql security definer set search_path=public,pg_catalog as $$declare total integer;correct integer;course uuid;max_tries integer;begin select course_id,max_attempts into course,max_tries from public.quizzes where id=p_quiz_id and is_published;if course is null or not exists(select 1 from public.enrollments e where e.course_id=course and e.student_id=auth.uid() and e.status='active') then raise exception 'Quiz unavailable';end if;if (select count(*) from public.quiz_attempts where quiz_id=p_quiz_id and student_id=auth.uid())>=max_tries then raise exception 'Maximum attempts reached';end if;select count(*),count(*) filter(where (p_answers->>k.question_id::text)::integer=k.correct_index) into total,correct from public.quiz_answer_keys k where k.quiz_id=p_quiz_id;insert into public.quiz_attempts(quiz_id,student_id,answers,score) values(p_quiz_id,auth.uid(),p_answers,round((correct::numeric/nullif(total,0))*100,2));return jsonb_build_object('score',round((correct::numeric/nullif(total,0))*100,2),'correct',correct,'total',total);end$$;
revoke all on function public.create_quiz_with_questions(uuid,text,integer,jsonb),public.submit_quiz_attempt(uuid,jsonb) from public,anon;grant execute on function public.create_quiz_with_questions(uuid,text,integer,jsonb),public.submit_quiz_attempt(uuid,jsonb) to authenticated;

-- Attendance codes are private and consumed through RPCs.
create table public.attendance_sessions(id uuid primary key default gen_random_uuid(),course_id uuid not null references public.courses on delete cascade,title text not null,starts_at timestamptz not null default now(),ends_at timestamptz not null,created_by uuid not null references public.profiles,created_at timestamptz not null default now());
create table public.attendance_codes(session_id uuid primary key references public.attendance_sessions on delete cascade,code_hash text not null unique);
create table public.attendance_records(id uuid primary key default gen_random_uuid(),session_id uuid not null references public.attendance_sessions on delete cascade,student_id uuid not null references public.profiles on delete cascade,status text not null default 'present' check(status in ('present','late','excused','absent')),checked_in_at timestamptz not null default now(),unique(session_id,student_id));
alter table public.attendance_sessions enable row level security;alter table public.attendance_codes enable row level security;alter table public.attendance_records enable row level security;
create policy "relevant users read attendance sessions" on public.attendance_sessions for select to authenticated using(public.teaches_course(course_id) or exists(select 1 from public.enrollments e where e.course_id=attendance_sessions.course_id and e.student_id=auth.uid() and e.status='active'));
create policy "staff manage attendance sessions" on public.attendance_sessions for all to authenticated using(public.teaches_course(course_id)) with check(public.teaches_course(course_id));
create policy "staff read attendance codes" on public.attendance_codes for select to authenticated using(exists(select 1 from public.attendance_sessions s where s.id=session_id and public.teaches_course(s.course_id)));
create policy "read relevant attendance records" on public.attendance_records for select to authenticated using(student_id=auth.uid() or exists(select 1 from public.attendance_sessions s where s.id=session_id and public.teaches_course(s.course_id)));
grant select on public.attendance_sessions,public.attendance_records to authenticated;
create or replace function public.create_attendance_session(p_course_id uuid,p_title text,p_code text,p_minutes integer) returns uuid language plpgsql security definer set search_path=public,pg_catalog as $$declare sid uuid;begin if not public.teaches_course(p_course_id) then raise exception 'Not allowed';end if;if char_length(trim(p_code))<4 then raise exception 'Code too short';end if;insert into public.attendance_sessions(course_id,title,ends_at,created_by) values(p_course_id,left(trim(p_title),160),now()+make_interval(mins=>greatest(5,least(p_minutes,180))),auth.uid()) returning id into sid;insert into public.attendance_codes(session_id,code_hash) values(sid,encode(digest(lower(trim(p_code)),'sha256'),'hex'));return sid;end$$;
create or replace function public.check_in_attendance(p_code text) returns text language plpgsql security definer set search_path=public,pg_catalog as $$declare sid uuid;course uuid;begin select s.id,s.course_id into sid,course from public.attendance_sessions s join public.attendance_codes c on c.session_id=s.id where c.code_hash=encode(digest(lower(trim(p_code)),'sha256'),'hex') and now() between s.starts_at and s.ends_at;if sid is null then raise exception 'Invalid or expired code';end if;if not exists(select 1 from public.enrollments e where e.course_id=course and e.student_id=auth.uid() and e.status='active') then raise exception 'Not enrolled';end if;insert into public.attendance_records(session_id,student_id) values(sid,auth.uid()) on conflict(session_id,student_id) do nothing;return 'تم تسجيل الحضور بنجاح';end$$;
revoke all on function public.create_attendance_session(uuid,text,text,integer),public.check_in_attendance(text) from public,anon;grant execute on function public.create_attendance_session(uuid,text,text,integer),public.check_in_attendance(text) to authenticated;

-- Support tickets.
create table public.support_threads(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles on delete cascade,subject text not null,status text not null default 'open' check(status in ('open','pending','closed')),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.support_messages(id uuid primary key default gen_random_uuid(),thread_id uuid not null references public.support_threads on delete cascade,sender_id uuid not null references public.profiles on delete cascade,body text not null check(char_length(body) between 1 and 3000),created_at timestamptz not null default now());
alter table public.support_threads enable row level security;alter table public.support_messages enable row level security;
create policy "users read own support threads" on public.support_threads for select to authenticated using(user_id=auth.uid() or public.current_role()='admin');create policy "users create support threads" on public.support_threads for insert to authenticated with check(user_id=auth.uid());create policy "admins update support threads" on public.support_threads for update to authenticated using(public.current_role()='admin') with check(public.current_role()='admin');
create policy "participants read support messages" on public.support_messages for select to authenticated using(exists(select 1 from public.support_threads t where t.id=thread_id and (t.user_id=auth.uid() or public.current_role()='admin')));create policy "participants send support messages" on public.support_messages for insert to authenticated with check(sender_id=auth.uid() and exists(select 1 from public.support_threads t where t.id=thread_id and t.status<>'closed' and (t.user_id=auth.uid() or public.current_role()='admin')));
grant select,insert on public.support_threads,public.support_messages to authenticated;grant update on public.support_threads to authenticated;

commit;
