import { db, auth, SUPER_ADMIN_EMAIL } from './firebase.js';
import { doc, onSnapshot, setDoc } from 'https://www.gstatic.com/firebasejs/9.23.0/firebase-firestore.js';
import { FEATURE_KEYS, OFFICIAL_MODE_DEFAULTS, normalizeFeatureFlags, isFeatureEnabled } from './featureFlags.js';

const LABELS={privateMessages:'الرسائل الخاصة',generalChat:'الشات العام',studyChat:'غرفة الدراسة',helpChat:'غرفة المساعدة',randomChat:'الغرفة العشوائية',socialFeed:'المنشورات الاجتماعية',follows:'المتابعة',leaderboard:'لوحة الشرف',xp:'نقاط XP',achievements:'الإنجازات',streak:'Streak',aiAssistant:'مساعد AI',videoCalls:'مكالمات الفيديو'};
let flags=normalizeFeatureFlags(OFFICIAL_MODE_DEFAULTS),isOwner=false,unsubscribeFlags=null,collegeRoomApplied=false,applyScheduled=false;
const selectors={privateMessages:['button[onclick*="openDMPanel"]','button[onclick*="openNewDM"]','button[onclick*="openDMFromProfile"]','button[onclick*="startDMWith"]','#dm-panel'],socialFeed:['a[href="#feed"]','a[href="#posts"]','#feed-section'],follows:['button[onclick*="toggleFollow"]'],leaderboard:['a[href="#leaderboard"]','#leaderboard-section','button[onclick*="openCollegeRankingPanel"]'],xp:['#xp-widget','#level-widget','[data-feature="xp"]'],achievements:['#achievements-widget','[data-feature="achievements"]'],videoCalls:['button[onclick*="startVideoCall"]'],aiAssistant:['#ai-chat-widget'],streak:['#streak-widget']};
window.isOfficialFeatureEnabled=key=>isFeatureEnabled(flags,key);
window.isOfficialModeOwner=()=>isOwner;
const setVisible=(el,visible)=>{if(!el)return;if(!visible){el.style.setProperty('display','none','important');el.setAttribute('aria-hidden','true');}else{el.style.removeProperty('display');el.removeAttribute('aria-hidden');}};
const applyRoomPolicy=()=>{document.querySelectorAll('.room-tab').forEach(tab=>setVisible(tab,tab.id==='college-room-tab'||tab.dataset.room==='college'||tab.dataset.room?.startsWith('college_')));const chat=document.getElementById('group-chat-window'),open=Boolean(chat&&!chat.classList.contains('hidden'));if(!open){collegeRoomApplied=false;return;}if(!collegeRoomApplied&&typeof window.switchToCollegeRoom==='function'){collegeRoomApplied=true;window.switchToCollegeRoom();}};
function closePanel(){document.getElementById('official-feature-panel')?.remove();}
const syncOwnerLink=()=>{const existing=document.getElementById('owner-extra-features-btn');if(!isOwner){existing?.remove();closePanel();return;}if(existing)return;const links=document.getElementById('admin-sidebar-links');if(!links)return;const btn=document.createElement('button');btn.id='owner-extra-features-btn';btn.className='w-full flex items-center gap-3 p-3 rounded-xl bg-slate-900 text-white font-bold';btn.innerHTML='<i class="fas fa-sliders-h w-6 text-center"></i><span>الميزات الإضافية</span>';btn.onclick=openPanel;links.appendChild(btn);};
const applyVisibility=()=>{Object.entries(selectors).forEach(([key,list])=>{const enabled=key==='leaderboard'?false:isFeatureEnabled(flags,key);list.forEach(sel=>document.querySelectorAll(sel).forEach(el=>setVisible(el,enabled)));});applyRoomPolicy();syncOwnerLink();};
const scheduleApply=()=>{if(applyScheduled)return;applyScheduled=true;requestAnimationFrame(()=>{applyScheduled=false;applyVisibility();});};
const guardRoutes=()=>{const route=location.hash.slice(1).split('/')[0];if(route==='leaderboard'&&!isOwner)location.hash='home';if((route==='feed'||route==='posts')&&!isFeatureEnabled(flags,'socialFeed'))location.hash='home';};
function openPanel(){if(!isOwner)return;closePanel();const overlay=document.createElement('div');overlay.id='official-feature-panel';overlay.className='fixed inset-0 z-[10000] bg-black/60 backdrop-blur-sm flex items-center justify-center p-4';overlay.innerHTML=`<div class="bg-white dark:bg-gray-800 w-full max-w-2xl max-h-[85vh] overflow-y-auto rounded-3xl shadow-2xl p-6"><div class="flex justify-between items-center mb-2"><h2 class="text-xl font-black dark:text-white">الميزات الإضافية</h2><button id="close-feature-panel" class="w-9 h-9 rounded-full bg-gray-100 dark:bg-gray-700">✕</button></div><p class="text-sm text-gray-500 mb-5">الوضع الرسمي افتراضي، وهذه الإعدادات للأونر فقط.</p><div class="space-y-2">${FEATURE_KEYS.map(key=>`<label class="flex items-center justify-between p-3 rounded-xl bg-gray-50 dark:bg-gray-700/50"><span class="font-bold dark:text-white">${LABELS[key]||key}</span><input type="checkbox" data-feature-toggle="${key}" class="w-5 h-5" ${isFeatureEnabled(flags,key)?'checked':''}></label>`).join('')}</div><button id="open-hidden-leaderboard" class="mt-5 w-full bg-gray-800 text-white py-3 rounded-xl font-bold">فتح لوحة الشرف للأونر</button></div>`;document.body.appendChild(overlay);overlay.onclick=e=>{if(e.target===overlay)closePanel();};overlay.querySelector('#close-feature-panel').onclick=closePanel;overlay.querySelector('#open-hidden-leaderboard').onclick=()=>{closePanel();location.hash='leaderboard';};overlay.querySelectorAll('[data-feature-toggle]').forEach(input=>{input.onchange=async()=>{input.disabled=true;try{await setDoc(doc(db,'system','feature_flags'),{[input.dataset.featureToggle]:input.checked},{merge:true});}catch{input.checked=!input.checked;window.showToast?.('تعذر حفظ إعداد الميزة','error');}finally{input.disabled=false;}};});}
new MutationObserver(scheduleApply).observe(document.documentElement,{childList:true,subtree:true,attributes:true,attributeFilter:['class']});
window.addEventListener('hashchange',guardRoutes);
document.addEventListener('click',e=>{const actions=[['privateMessages','[onclick*="openDMPanel"], [onclick*="openNewDM"], [onclick*="openDMFromProfile"], [onclick*="startDMWith"]'],['follows','[onclick*="toggleFollow"]'],['videoCalls','[onclick*="startVideoCall"]'],['leaderboard','[onclick*="openCollegeRankingPanel"]']];for(const [feature,selector] of actions){if(e.target.closest?.(selector)&&!(feature==='leaderboard'&&isOwner)&&!isFeatureEnabled(flags,feature)){e.preventDefault();e.stopImmediatePropagation();return;}}},true);
auth.onAuthStateChanged(user=>{isOwner=user?.email===SUPER_ADMIN_EMAIL;if(unsubscribeFlags){unsubscribeFlags();unsubscribeFlags=null;}if(!user){flags=normalizeFeatureFlags();applyVisibility();guardRoutes();return;}unsubscribeFlags=onSnapshot(doc(db,'system','feature_flags'),snap=>{flags=normalizeFeatureFlags(snap.exists()?snap.data():OFFICIAL_MODE_DEFAULTS);applyVisibility();guardRoutes();});});
window.openOfficialFeatureSettings=openPanel;
