import {BookOpen,CalendarDays,Download,FileText,Megaphone,Upload,Users} from 'lucide-react';import {useEffect,useState} from 'react';import {supabase} from '../lib/supabase';import {useAuth} from '../context/AuthContext';
const Stat=({icon:Icon,label,value})=><article className="stat"><Icon/><div><strong>{value}</strong><span>{label}</span></div></article>;
export function StudentHome(){return <><div className="pageTitle"><div><span>مرحباً بك</span><h1>لوحة الطالب</h1><p>تابع موادك وآخر الملفات الأكاديمية.</p></div></div><div className="stats"><Stat icon={BookOpen} label="المقررات الحالية" value="—"/><Stat icon={FileText} label="ملفات جديدة" value="—"/><Stat icon={CalendarDays} label="مهام قادمة" value="—"/><Stat icon={Megaphone} label="إعلانات" value="—"/></div><Courses/></>}
export function FacultyHome(){return <><div className="pageTitle"><div><span>مساحة العمل الأكاديمية</span><h1>لوحة عضو هيئة التدريس</h1><p>إدارة المقررات ونشر المواد للطلاب.</p></div></div><div className="stats"><Stat icon={BookOpen} label="المقررات" value="—"/><Stat icon={Users} label="الطلاب" value="—"/><Stat icon={FileText} label="المواد المنشورة" value="—"/><Stat icon={Upload} label="مسودات" value="—"/></div><Courses faculty/></>}
export function Courses({faculty=false}){const {profile}=useAuth();const [rows,setRows]=useState([]);const [loading,setLoading]=useState(true);useEffect(()=>{if(!supabase||!profile)return;const relation=faculty?'course_staff!inner(profile_id)':'enrollments!inner(student_id)';supabase.from('courses').select(`id,code,title,term,academic_year,${relation}`).eq(faculty?'course_staff.profile_id':'enrollments.student_id',profile.id).eq('is_published',true).then(({data})=>{setRows(data||[]);setLoading(false);});},[profile,faculty]);return <div className="contentBlock"><div className="blockHead"><div><h2>{faculty?'مقرراتي':'المقررات الحالية'}</h2><p>المحتوى الأكاديمي المتاح خلال الفصل الحالي</p></div></div>{loading?<p className="muted">جاري تحميل المقررات…</p>:rows.length?<div className="courseGrid">{rows.map(c=><article className="courseCard" key={c.id}><span>{c.code}</span><BookOpen/><h3>{c.title}</h3><p>{c.term} • {c.academic_year}</p><button>فتح المقرر</button></article>)}</div>:<div className="empty"><BookOpen/><h3>لا توجد مقررات مرتبطة بالحساب</h3><p>ستظهر المقررات هنا بعد تسجيلها من الإدارة.</p></div>}</div>}
export function Materials(){return <div className="contentBlock"><div className="blockHead"><div><h1>المكتبة والملفات</h1><p>الكتب والمذكرات والمحاضرات المنشورة في مقرراتك.</p></div></div><div className="empty"><Download/><h3>اختر مقررًا لعرض ملفاته</h3></div></div>}
export function Announcements(){return <div className="contentBlock"><div className="blockHead"><div><h1>الإعلانات</h1><p>التحديثات الرسمية الخاصة بمقرراتك والجامعة.</p></div></div><div className="empty"><Megaphone/><h3>لا توجد إعلانات جديدة</h3></div></div>}
export function UploadMaterial(){const [file,setFile]=useState(null);const [title,setTitle]=useState('');const [courseId,setCourseId]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const {profile}=useAuth();async function submit(e){e.preventDefault();if(!file||!courseId)return;setBusy(true);const path=`${courseId}/${crypto.randomUUID()}-${file.name}`;const {error:uploadError}=await supabase.storage.from('course-materials').upload(path,file);if(uploadError){setMessage('فشل رفع الملف.');setBusy(false);return;}const {error}=await supabase.from('materials').insert({course_id:courseId,title,file_path:path,file_name:file.name,mime_type:file.type,size_bytes:file.size,uploaded_by:profile.id,status:'published'});setMessage(error?'فشل حفظ بيانات الملف.':'تم رفع المادة ونشرها بنجاح.');setBusy(false);}return <div className="contentBlock narrow"><div className="blockHead"><div><h1>رفع مادة علمية</h1><p>أضف كتابًا أو مذكرة أو ملف محاضرة إلى مقرر.</p></div></div><form className="uploadForm" onSubmit={submit}><label>معرّف المقرر<input value={courseId} onChange={e=>setCourseId(e.target.value)} placeholder="UUID" required/></label><label>عنوان المادة<input value={title} onChange={e=>setTitle(e.target.value)} required/></label><label className="drop"><Upload/><strong>{file?file.name:'اختر ملفًا للرفع'}</strong><span>PDF أو PowerPoint أو Word</span><input type="file" accept=".pdf,.ppt,.pptx,.doc,.docx" onChange={e=>setFile(e.target.files[0])} required/></label>{message&&<p>{message}</p>}<button disabled={busy}>{busy?'جاري الرفع…':'رفع ونشر'}</button></form></div>}
export function Students(){return <div className="contentBlock"><div className="blockHead"><div><h1>الطلاب</h1><p>قوائم الطلاب المسجلين في مقرراتك.</p></div></div><div className="empty"><Users/><h3>اختر مقررًا لعرض الطلاب</h3></div></div>}
