import {Navigate,useNavigate} from 'react-router-dom';
import {useState} from 'react';
import Brand from '../components/Brand';import Icon from '../components/Icon';import ThemeToggle from '../components/ThemeToggle';
import {useAuth} from '../context/AuthContext';import {isSupabaseConfigured} from '../lib/supabase';import {cleanText} from '../lib/validation';import {portalAllows,portalName,roleHome} from '../lib/portal';

export function Landing(){const nav=useNavigate();return <div className="landing"><header><Brand/><div className="headerActions"><ThemeToggle/><button onClick={()=>nav('/login')}>تسجيل الدخول</button></div></header><main><div className="heroCopy"><span className="eyebrow">{portalName}</span><h1>تعليم جامعي منظم، في بوابة واحدة.</h1><p>وصول واضح إلى الكتب والمذكرات والمحاضرات والواجبات.</p><button onClick={()=>nav('/login')}>الدخول إلى البوابة</button></div><div className="bookPanel"><Icon name="book"/><strong>المكتبة الرقمية</strong><span>المقررات • الكتب • المحاضرات • الملفات</span></div></main></div>}
const attempts={count:0,until:0};
export function Login(){const {session,profile,loading,client,signOut}=useAuth(),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  if(!loading&&session&&profile){if(!portalAllows(profile.role))return <div className="loginPage"><div className="loginCard"><Brand/><h1>بوابة غير صحيحة</h1><p>هذا الحساب لا يخص {portalName}.</p><button onClick={signOut}>تسجيل الخروج</button></div></div>;return <Navigate to={roleHome(profile.role)} replace/>;}
  if(!loading&&session&&!profile)return <div className="loginPage"><div className="loginCard"><Brand/><h1>الحساب غير مهيأ</h1><p>تواصل مع إدارة النظام.</p><button onClick={signOut}>تسجيل الخروج</button></div></div>;
  async function submit(e){e.preventDefault();const now=Date.now();if(attempts.until>now){setError('انتظر قليلًا قبل المحاولة.');return;}if(!isSupabaseConfigured||!client){setError('لم يتم ربط Supabase بعد.');return;}setBusy(true);setError('');try{const {error:err}=await client.auth.signInWithPassword({email:cleanText(email,254).toLowerCase(),password});if(err){attempts.count++;if(attempts.count>=5){attempts.until=now+300000;attempts.count=0;}setError('تعذر تسجيل الدخول.');}else{attempts.count=0;attempts.until=0;}}catch{setError('تعذر الاتصال بالخدمة.');}finally{setBusy(false);}}
  return <div className="loginPage"><div className="loginCard"><Brand/><h1>{portalName}</h1><p>سجل الدخول بحسابك الجامعي.</p><form onSubmit={submit}><label>البريد الجامعي<input type="email" autoComplete="username" maxLength="254" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>كلمة المرور<input type="password" autoComplete="current-password" minLength="8" maxLength="128" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{error&&<div className="error" role="alert">{error}</div>}<button disabled={busy||loading}>{busy?'جاري الدخول…':'دخول'}</button></form></div></div>}
